config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'about', :to => 'home#about'

  # get 'help', :to => 'home#help'

  get 'terms', :to => 'home#terms'

  get 'privacy', :to => 'home#privacy'

  get 'inquiry', :to => 'inquiry#index'
  post 'inquiry' => 'inquiry#confirm'

  devise_for :users, skip: :all
  devise_scope :user do
    # ユーザ登録
    get 'sign_up', :to => 'users/registrations#new'
    post 'sign_up', :to => 'users/registrations#create'
    # ログイン
    get 'login', :to => 'users/sessions#new', as: :new_user_session
    post 'login', :to => 'users/sessions#create'
    # ログアウト
    delete 'logout', :to => 'users/sessions#destroy'
    # ユーザ編集
    get 'user' => 'users/registrations#edit'
    patch 'user' => 'users/registrations#update'
    put 'user' => 'users/registrations#update'
    delete 'user' => 'users/registrations#destroy'
    # ユーザ認証
    get 'users/confirmation', to: 'users/confirmations#show', as: 'confirmation_token'
    post 'users/confirmation', to: 'users/confirmations#create', as: 'confirmation_token_create'
    get 'users/confirmation/new', to: 'users/confirmations#new', as: 'confirmation_token_new'
    # パスワードリセット
    get 'password' => 'users/passwords#new', as: :new_user_password
    post 'password' => 'users/passwords#create', as: :user_password
    get 'password/reset/:reset_password_token' => 'users/passwords#edit', as: :edit_user_password
    patch 'password' => 'users/passwords#update'
    put 'password' => 'users/passwords#update', as: :update_user_password
  end

  resources :users, only: :show, :as => 'user_show' do
    resources :posts, only: [:show]
    get '/posts', :to => 'posts#users_index', :as => 'users_index'
  end
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'

  resources :posts, only: [:new, :edit]
  post '/posts/new', :to => 'posts#create'
  patch '/posts/:id/edit', :to => 'posts#update', :as => 'posts_edit'
  resources :categories do
    resources :posts, only: [:index, :show]
    post '/posts/:id', :to => 'replies#create', :as => 'reply'
  end

  if Rails.env.production?
    get '*not_found' => 'application#routing_error'
    post '*not_found' => 'application#routing_error'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = PostDecorator.decorate_collection(Post.default_order.limit(6))
  end

  def about; end
  # def help; end
  # def terms; end
  # def privacy; end
end

app/views/home/about.html.erb
<% @page_title = 'メンタリーとは' %>

<div class="box">
  <h1 class="title is-6">メンタリーとは</h1>
  <hr>
  <div class="content is-size-7">
    <p>メンタリーとは、様々なメンタルに関する症状・悩み等、みんなの声を集め、お互いに問題を解決していく場所です。</p>
    <p>同じ悩みを持つ人同士で交流を目的しています。同じ悩みならお互い分かち合い、アドバイスし合えると思います。</p>
    <p>利用に関しては、完全無料です。</p>
    <% if !user_signed_in? %><p><%= link_to('登録はこちらから', sign_up_path) %></p><% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="box">
  <h1 class="title is-6">新着投稿</h1>
  <hr>
  <% if @posts.present? %>
    <% @posts.each do |post| %>
    <article class="content post">
      <div class="title is-size-5 has-margin-b-6">
        <%= link_to(post.subject, category_post_path(post.category, post)) %>
      </div>
      <div class="media">
        <div class="media-left">
          <p class="image is-32x32">
            <%= image_tag(post.user_avatar_icon_url, class: 'is-rounded') %>
          </p>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <% if post.user.nil? %><%= post.not_exist_post_user %><% else %><%= link_to(post.user.name, user_show_path(post.user)) %><% end %> &nbsp;<span class="tag"><%= post.category.name %></span>
            </p>
          </div>
        </div>
        <div class="media-right">
          <span class="has-text-grey-light"><i class="fa fa-comments"></i> <%= post.reply_count %></span>
        </div>
      </div>
    </article>
    <% end %>
  <% end %>
</div>

app/views/home/privacy.html.erb
<% @page_title = 'プライバシーポリシー' %>

<div class="privacy box">
  <h1 class="title is-6">プライバシーポリシー</h1>
  <hr>

  <p class="is-size-7">
    Mentally（以下、「当社」といいます。）は、本ウェブサイト上で提供するサービス（以下,「本サービス」）におけるプライバシー情報の取扱いについて、
    以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。
  </p>

  <div class="content">
    <div class="title is-7">第1条（プライバシー情報）</div>
    <ul class="is-size-7">
      <li>プライバシー情報のうち「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報を指します。</li>
      <li>プライバシー情報のうち「履歴情報および特性情報」とは、上記に定める「個人情報」以外のものをいい、ご利用いただいたサービスやご購入いただいた商品、ご覧になったページや広告の履歴、ユーザーが検索された検索キーワード、ご利用日時、ご利用の方法、ご利用環境、郵便番号や性別、職業、年齢、ユーザーのIPアドレス、クッキー情報、位置情報、端末の個体識別情報などを指します。</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第２条（プライバシー情報の収集方法）</div>
    <ul class="is-size-7">
      <li>当社は、ユーザーが利用登録をする際に氏名、生年月日、住所、電話番号、メールアドレス、銀行口座番号、クレジットカード番号、運転免許証番号などの個人情報をお尋ねすることがあります。また、ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や、決済に関する情報を当社の提携先（情報提供元、広告主、広告配信先などを含みます。以下、｢提携先｣といいます。）などから収集することがあります。</li>
      <li>当社は、ユーザーについて、利用したサービスやソフトウエア、購入した商品、閲覧したページや広告の履歴、検索した検索キーワード、利用日時、利用方法、利用環境（携帯端末を通じてご利用の場合の当該端末の通信状態、利用に際しての各種設定情報なども含みます）、IPアドレス、クッキー情報、位置情報、端末の個体識別情報などの履歴情報および特性情報を、ユーザーが当社や提携先のサービスを利用しまたはページを閲覧する際に収集します。</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第３条（個人情報を収集・利用する目的）</div>
    <p class="is-size-7">
      当社が個人情報を収集・利用する目的は、以下のとおりです。
    </p>
    <ul class="is-size-7">
      <li>ユーザーに自分の登録情報の閲覧や修正、利用状況の閲覧を行っていただくために、氏名、住所、連絡先、支払方法などの登録情報、利用されたサービスや購入された商品、およびそれらの代金などに関する情報を表示する目的</li>
      <li>ユーザーにお知らせや連絡をするためにメールアドレスを利用する場合やユーザーに商品を送付したり必要に応じて連絡したりするため、氏名や住所などの連絡先情報を利用する目的</li>
      <li>ユーザーの本人確認を行うために、氏名、生年月日、住所、電話番号、銀行口座番号、クレジットカード番号、運転免許証番号、配達証明付き郵便の到達結果などの情報を利用する目的</li>
      <li>ユーザーに代金を請求するために、購入された商品名や数量、利用されたサービスの種類や期間、回数、請求金額、氏名、住所、銀行口座番号やクレジットカード番号などの支払に関する情報などを利用する目的</li>
      <li>ユーザーが簡便にデータを入力できるようにするために、当社に登録されている情報を入力画面に表示させたり、ユーザーのご指示に基づいて他のサービスなど（提携先が提供するものも含みます）に転送したりする目的</li>
      <li>代金の支払を遅滞したり第三者に損害を発生させたりするなど、本サービスの利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの利用をお断りするために、利用態様、氏名や住所など個人を特定するための情報を利用する目的</li>
      <li>ユーザーからのお問い合わせに対応するために、お問い合わせ内容や代金の請求に関する情報など当社がユーザーに対してサービスを提供するにあたって必要となる情報や、ユーザーのサービス利用状況、連絡先情報などを利用する目的</li>
      <li>上記の利用目的に付随する目的</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第４条（個人情報の第三者提供）</div>
    <p class="is-size-7">
      当社は、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。
    </p>
    <ul class="is-size-7">
      <ul class="is-size-7">
        <li>法令に基づく場合</li>
        <li>人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき</li>
        <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき</li>
        <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
        <li>予め次の事項を告知あるいは公表をしている場合</li>
        <ol>
          <li>利用目的に第三者への提供を含むこと</li>
          <li>第三者に提供されるデータの項目</li>
          <li>第三者への提供の手段または方法</li>
          <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
        </ol>
      </ul>
    </ul>
    <p class="is-size-7">前項の定めにかかわらず、次に掲げる場合は第三者には該当しないものとします。</p>
    <ul class="is-size-7">
      <li>当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
      <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
      <li>個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報の項目、共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、あらかじめ本人に通知し、または本人が容易に知り得る状態に置いているとき</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第５条（個人情報の開示）</div>
    <p class="is-size-7">
      当社は、ユーザーから、個人情報保護法の定めに基づき個人情報の開示を求められた時は、ユーザーご本人からのご請求であることを確認の上で、ユーザーに対し、遅滞なく開示を行います（当該個人情報が存在しないときにはその旨を通知いたします。）。但し、個人情報保護法その他の法令により、当社が開示の義務を負わない場合は、この限りではありません。なお、個人情報の開示につきましては、手数料(1件あたり2,000円)を頂戴しておりますので、あらかじめご了承ください。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第６条（個人情報の訂正および削除）</div>
    <ul class="is-size-7">
      <li>ユーザーは、当社の保有する自己の個人情報が誤った情報である場合には、当社が定める手続きにより、当社に対して個人情報の訂正または削除を請求することができます。</li>
      <li>当社は、ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の訂正または削除を行い、これをユーザーに通知します。</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第７条（個人情報の利用停止等）</div>
    <p class="is-size-7">
      当社は、本人から、個人情報が、利用目的の範囲を超えて取り扱われているという理由、または不正の手段により取得されたものであるという理由により、その利用の停止または消去（以下、「利用停止等」といいます。）を求められた場合には、遅滞なく必要な調査を行い、その結果に基づき、個人情報の利用停止等を行い、その旨本人に通知します。ただし、個人情報の利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって、本人の権利利益を保護するために必要なこれに代わるべき措置をとれる場合は、この代替策を講じます。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第８条（プライバシーポリシーの変更）</div>
    <ul class="is-size-7">
      <li>本ポリシーの内容は、ユーザーに通知することなく、変更することができるものとします。</li>
      <li>当社が別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第９条（お問い合わせ窓口）</div>
    <p class="is-size-7">
      本ポリシーに関するお問い合わせは、下記の窓口までお願いいたします。</p>
    </p>
    <p class="is-size-7"><%= link_to 'お問い合わせフォーム', inquiry_path %></p>
  </div>

</div>

app/views/home/terms.html.erb
<% @page_title = '利用規約' %>

<div class="terms box">
  <h1 class="title is-6">利用規約</h1>
  <hr>

  <p class="is-size-7">
    この利用規約（以下、「本規約」といいます。）は Mentally（以下、「当社」）がこのウェブサイト上で提供するサービス（以下、「本サービス」）の利用条件を定めるものです。
    登録ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。
  </p>

  <div class="content">
    <div class="title is-7">第1条（適用）</div>
    <p class="is-size-7">
      本規約は、ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第2条（利用登録）</div>
    <p class="is-size-7">
      登録希望者が当社の定める方法によって利用登録を申請し、当社がこれを承認することによって、利用登録が完了するものとします。<br>
      当社は、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。
    </p>
    <ul class="is-size-7">
      <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
      <li>本規約に違反したことがある者からの申請である場合</li>
      <li>反社会的勢力等（暴力団、暴力団員、右翼団体、反社会的勢力、その他これに準ずる者を意味します。）である、または資金提供その他を通じて反社会的勢力等の維持、運営もしくは経営に協力もしくは関与する等反社会的勢力との何らかの交流もしくは関与を行っていると当社が判断した場合</li>
      <li>その他、当社が利用登録を相当でないと判断した場合</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第3条（ユーザーIDおよびパスワードの管理）</div>
    <ul class="is-size-7">
      <li>ユーザーは、自己の責任において、本サービスのユーザーIDおよびパスワードを管理するものとします。</li>
      <li>ユーザーは、いかなる場合にも、ユーザーIDおよびパスワードを第三者に譲渡または貸与することはできません。当社は、ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には、そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第4条（禁止事項）</div>
    <p class="is-size-7">
      ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。
    </p>
    <ul class="is-size-7">
      <li>法令または公序良俗に違反する行為</li>
      <li>犯罪行為に関連する行為</li>
      <li>当社のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為</li>
      <li>当社のサービスの運営を妨害するおそれのある行為</li>
      <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
      <li>他のユーザーに成りすます行為</li>
      <li>当社のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為</li>
      <li>当社、本サービスの他の利用者または第三者の知的財産権、肖像権、プライバシー、名誉その他の権利または利益を侵害する行為</li>
      <li>過度に暴力的な表現、露骨な性的表現、人種、国籍、信条、性別、社会的身分、門地等による差別につながる表現、自殺、自傷行為、薬物乱用を誘引または助長する表現、その他反社会的な内容を含み他人に不快感を与える表現を、投稿または送信する行為</li>
      <li>営業、宣伝、広告、勧誘、その他営利を目的とする行為（当社の認めたものを除きます。）、性行為やわいせつな行為を目的とする行為、面識のない異性との出会いや交際を目的とする行為、他のお客様に対する嫌がらせや誹謗中傷を目的とする行為、その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
      <li>宗教活動または宗教団体への勧誘行為</li>
      <li>その他、当社が不適切と判断する行為</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第5条（本サービスの提供の停止等）</div>
    <p class="is-size-7">
      当社は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
      また、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害について、理由を問わず一切の責任を負わないものとします。
    </p>
    <ul class="is-size-7">
      <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
      <li>地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合</li>
      <li>コンピュータまたは通信回線等が事故により停止した場合</li>
      <li>その他、当社が本サービスの提供が困難と判断した場合</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第6条（著作権）</div>
    <ul class="is-size-7">
      <li>ユーザーは、自ら著作権等の必要な知的財産権を有するか、または必要な権利者の許諾を得た文章、画像や映像等の情報のみ、本サービスを利用し、投稿または編集することができるものとします。</li>
      <li>ユーザーが本サービスを利用して投稿または編集した文章、画像、映像等の著作権については、当該ユーザーその他既存の権利者に留保されるものとします。ただし、当社は、本サービスを利用して投稿または編集された文章、画像、映像等を利用できるものとし、ユーザーは、この利用に関して、著作者人格権を行使しないものとします。</li>
      <li>前項本文の定めるものを除き、本サービスおよび本サービスに関連する一切の情報についての著作権およびその他知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し、ユーザーは無断で複製、譲渡、貸与、翻訳、改変、転載、公衆送信（送信可能化を含みます。）、伝送、配布、出版、営業使用等をしてはならないものとします。</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第7条（利用制限および登録抹消）</div>
    <p class="is-size-7">
      当社は、以下の場合には、事前の通知なく、投稿データを削除し、ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
    </p>
    <ul class="is-size-7">
      <li>本規約のいずれかの条項に違反した場合</li>
      <li>登録事項に虚偽の事実があることが判明した場合</li>
      <li>1年間以上本サービスの利用がない場合</li>
      <li>当社からの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合</li>
      <li>その他、当社が本サービスの利用を適当でないと判断した場合</li>
    </ul>
    <p class="is-size-7">
      上記のいずれかに該当した場合、ユーザーは、当然に当社に対する一切の債務について期限の利益を失い、その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。<br>
      当社は、本条に基づき当社が行った行為によりユーザーに生じた損害について、一切の責任を負いません。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第8条（保証の否認および免責事項）</div>
    <ul class="is-size-7">
      <li>当社は、本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
      <li>当社は、本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。</li>
      <li>当社は、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。</li>
    </ul>
  </div>

  <div class="content">
    <div class="title is-7">第9条（サービス内容の変更等）</div>
    <p class="is-size-7">
      当社は、ユーザーに通知することなく、本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし、これによってユーザーに生じた損害について一切の責任を負いません。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第10条（利用規約の変更）</div>
    <p class="is-size-7">
      当社は、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第11条（通知または連絡）</div>
    <p class="is-size-7">
      ユーザーと当社との間の通知または連絡は、当社の定める方法によって行うものとします。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第12条（権利義務の譲渡の禁止）</div>
    <p class="is-size-7">
      ユーザーは、当社の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。
    </p>
  </div>

  <div class="content">
    <div class="title is-7">第13条（準拠法・裁判管轄）</div>
    <ul class="is-size-7">
      <li>本規約の解釈にあたっては、日本法を準拠法とします。</li>
      <li>本サービスに関して紛争が生じた場合には、当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
    </ul>
  </div>

</div>