config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'about', :to => 'home#about'

  # get 'help', :to => 'home#help'

  get 'terms', :to => 'home#terms'

  get 'privacy', :to => 'home#privacy'

  get 'inquiry', :to => 'inquiry#index'
  post 'inquiry' => 'inquiry#confirm'

  devise_for :users, skip: :all
  devise_scope :user do
    # ユーザ登録
    get 'sign_up', :to => 'users/registrations#new'
    post 'sign_up', :to => 'users/registrations#create'
    # ログイン
    get 'login', :to => 'users/sessions#new', as: :new_user_session
    post 'login', :to => 'users/sessions#create'
    # ログアウト
    delete 'logout', :to => 'users/sessions#destroy'
    # ユーザ編集
    get 'user' => 'users/registrations#edit'
    patch 'user' => 'users/registrations#update'
    put 'user' => 'users/registrations#update'
    delete 'user' => 'users/registrations#destroy'
    # ユーザ認証
    get 'users/confirmation', to: 'users/confirmations#show', as: 'confirmation_token'
    post 'users/confirmation', to: 'users/confirmations#create', as: 'confirmation_token_create'
    get 'users/confirmation/new', to: 'users/confirmations#new', as: 'confirmation_token_new'
    # パスワードリセット
    get 'password' => 'users/passwords#new', as: :new_user_password
    post 'password' => 'users/passwords#create', as: :user_password
    get 'password/reset/:reset_password_token' => 'users/passwords#edit', as: :edit_user_password
    patch 'password' => 'users/passwords#update'
    put 'password' => 'users/passwords#update', as: :update_user_password
  end

  resources :users, only: :show, :as => 'user_show' do
    resources :posts, only: [:show]
    get '/posts', :to => 'posts#users_index', :as => 'users_index'
  end
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'

  resources :posts, only: [:new, :edit]
  post '/posts/new', :to => 'posts#create'
  patch '/posts/:id/edit', :to => 'posts#update', :as => 'posts_edit'
  resources :categories do
    resources :posts, only: [:index, :show]
    post '/posts/:id', :to => 'replies#create', :as => 'reply'
  end

  if Rails.env.production?
    get '*not_found' => 'application#routing_error'
    post '*not_found' => 'application#routing_error'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  belongs_to :category
  has_many :replies

  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :subject, presence: true, length: { maximum: 100 }
  validates :body, presence: true, length: { maximum: 2000 }

  scope :default_order, -> { order(created_at: :desc) }

  def reply_count
    if replies.loaded?
      replies.to_a.count
    else
      replies.count
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @category = @categories.find(params[:category_id])
    @posts = Post
              .where(category_id: params[:category_id])
              .page(params[:page])
              .per(6)
              .default_order
  end

  def users_index
    @user = User.find(params[:user_show_id]).decorate
    @posts = Post
              .where(user_id: params[:user_show_id])
              .page(params[:page])
              .per(10)
              .default_order
  end

  def show
    @reply = Reply.new
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if @post.save
      redirect_to category_post_path(@post.category_id, @post.id), notice: '記事を投稿しました。'
    else
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    if @post.update(post_params)
      redirect_to category_post_path(@post.category_id, @post.id), notice: '投稿を更新しました。'
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:subject, :category_id, :body)
  end

  def set_post
    @post = Post.find(params[:id]).decorate
  end
end

app/views/posts/_form.html.erb
<% @page_title = @post.new_record? ? '投稿' : '更新' %>

<% if @post.errors.any? %>
<div class="notification is-danger">
<% @post.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>
</div>
<% end %>

<%= form_for(@post, :url => (@post.new_record? ? posts_new_path : posts_edit_path)) do |f| %>
<div class="box">
  <h1 class="title is-6"><%= @post.new_record? ? '質問を投稿' : '質問を更新' %></h1>
  <hr>
  <div class="field is-small">
    <%= f.label :subject, 'タイトル', class: 'label is-small' %>
    <div class="control">
      <%= f.text_field :subject, class: 'input is-small', placeholder: 'わからないこと、聞きたいことをお書きください' %>
    </div>
  </div>
  <div class="field">
    <%= f.label :category_id, 'カテゴリー', class: 'label is-small' %>
    <div class="control">
      <div class="select is-small">
        <%= f.select :category_id, @categories.collect { |c| [ c.name, c.id ] }, { :prompt => '選択してください' } %>
      </div>
    </div>
  </div>
  <div class="field">
    <%= f.label :body, '本文', class: 'label is-small' %>
    <div class="control">
      <%= f.text_area :body, size: '20x10', class: 'textarea is-small', placeholder: '質問内容をお書きください' %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.submit (@post.new_record? ? '投稿' : '更新'), class: 'button is-small is-fullwidth' %>
    </div>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% @page_title = @category.name %>

<div class="box">
  <h1 class="title is-6">「<%= @category.name %>」の質問一覧</h1>
  <hr>
  <% if @posts.present? %>
    <% @posts.each do |post| %>
    <% post = post.decorate %>
    <article class="content post">
      <div class="title is-size-5 has-margin-b-6">
        <%= link_to(post.subject, category_post_path(post.category, post)) %>
      </div>
      <div class="media">
        <div class="media-left">
          <p class="image is-32x32">
            <%= image_tag(post.user_avatar_icon_url, class: 'is-rounded') %>
          </p>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <% if post.user.nil? %><%= post.not_exist_post_user %><% else %><%= link_to(post.user.name, user_show_path(post.user)) %><% end %> &nbsp;<span class="tag"><%= post.category.name %></span>
            </p>
          </div>
        </div>
        <div class="media-right">
          <span class="has-text-grey-light"><i class="fa fa-comments"></i> <%= post.reply_count %></span>
        </div>
      </div>
    </article>
    <% end %>
    <%= paginate @posts %>
  <% else %>
  <div class="content">
    <p>「<%= @category.name %>」に関して、お困りのことがあれば質問してみましょう。</p>
    <% if !user_signed_in? %>
    <p><%= link_to('ユーザ登録はこちらから', sign_up_path) %></p>
    <% else %>
    <p><%= link_to('質問する', new_post_path) %></p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<% @page_title = @post.subject %>

<% if @reply.errors.any? %>
<div class="notification is-danger">
  <% @reply.errors.full_messages.each do |message| %>
  <p><%= message %></p>
  <% end %>
</div>
<% end %>

<div class="box">
  <h1 class="title is-6"><%= @post.subject %></h1>
  <hr>
  <article class="media">
    <figure class="media-left">
      <p class="image is-64x64">
        <%= image_tag(@post.user_avatar_icon_url, class: 'is-rounded') %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <strong><% if @post.user.nil? %><%= @post.not_exist_post_user %><% else %><%= link_to(@post.user.name, user_show_path(@post.user)) %><% end %></strong>
        <%= @post.body_view %>
        <small class="has-text-grey">投稿日: <%= @post.created_at_view %></small>
      </div>
      <!-- reply start -->
      <% replies = ReplyDecorator.decorate_collection(@post.replies) %>
      <% if replies.present? %>
        <% replies.each do |reply| %>
        <article class="media">
          <figure class="media-left">
            <p class="image is-48x48">
              <%= image_tag(reply.user_avatar_icon_url, class: 'is-rounded') %>
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <strong><% if reply.user.nil? %><%= reply.not_exist_reply_user %><% else %><%= link_to(reply.user.name, user_show_path(reply.user)) %><% end %></strong>
              <%= reply.body_view %>
              <small class="has-text-grey">投稿日: <%= reply.created_at_view %></small>
            </div>
          </div>
        </article>
        <% end %>
      <% end %>
      <!-- reply end -->
    </div>
  </article>
  <% if user_signed_in? %>
  <!-- comment form start -->
  <%= form_for @reply, :url => category_reply_path, :html => {:class => "media"} do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <figure class="media-left">
    <p class="image is-64x64">
      <%= image_tag(current_user.avatar_icon_url, class: 'is-rounded') %>
    </p>
  </figure>
  <div class="media-content">
    <div class="field">
      <p class="control">
        <%= f.text_area :body, size: '20x3', class: 'textarea is-small', placeholder: '' %>
      </p>
    </div>
    <div class="field">
      <p class="control">
        <%= f.submit 'コメントする', class: 'button is-small is-fullwidth' %>
      </p>
    </div>
  </div>
  <% end %>
  <!-- comment form end -->
  <% end %>
</div>

app/views/posts/users_index.html.erb
<% @page_title = "#{@user.name}の質問一覧" %>

<div class="box">
  <h1 class="title is-6"><%= "#{@user.name}の質問一覧" %></h1>
  <hr>
  <% if @posts.present? %>
    <% @posts.each do |post| %>
    <% post = post.decorate %>
    <article class="content post">
      <div class="title is-size-5 has-margin-b-6">
        <%= link_to(post.subject, category_post_path(post.category, post)) %>
      </div>
      <div class="media">
        <div class="media-left">
          <p class="image is-32x32">
            <%= image_tag(post.user_avatar_icon_url, class: 'is-rounded') %>
          </p>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <% if user_signed_in? && current_user.id == @user.id %>
              <%= link_to('編集', posts_edit_path(post.id)) %>
              <% else %>
              <% if post.user.nil? %><%= post.not_exist_post_user %><% else %><%= link_to(post.user.name, user_show_path(post.user)) %><% end %>
              <% end %>
               &nbsp;<span class="tag"><%= post.category.name %></span>
            </p>
          </div>
        </div>
        <div class="media-right">
          <span class="has-text-grey-light"><i class="fa fa-comments"></i> <%= post.reply_count %></span>
        </div>
      </div>
    </article>
    <% end %>
    <%= paginate @posts %>
  <% end %>
</div>