config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'about', :to => 'home#about'

  # get 'help', :to => 'home#help'

  get 'terms', :to => 'home#terms'

  get 'privacy', :to => 'home#privacy'

  get 'inquiry', :to => 'inquiry#index'
  post 'inquiry' => 'inquiry#confirm'

  devise_for :users, skip: :all
  devise_scope :user do
    # ユーザ登録
    get 'sign_up', :to => 'users/registrations#new'
    post 'sign_up', :to => 'users/registrations#create'
    # ログイン
    get 'login', :to => 'users/sessions#new', as: :new_user_session
    post 'login', :to => 'users/sessions#create'
    # ログアウト
    delete 'logout', :to => 'users/sessions#destroy'
    # ユーザ編集
    get 'user' => 'users/registrations#edit'
    patch 'user' => 'users/registrations#update'
    put 'user' => 'users/registrations#update'
    delete 'user' => 'users/registrations#destroy'
    # ユーザ認証
    get 'users/confirmation', to: 'users/confirmations#show', as: 'confirmation_token'
    post 'users/confirmation', to: 'users/confirmations#create', as: 'confirmation_token_create'
    get 'users/confirmation/new', to: 'users/confirmations#new', as: 'confirmation_token_new'
    # パスワードリセット
    get 'password' => 'users/passwords#new', as: :new_user_password
    post 'password' => 'users/passwords#create', as: :user_password
    get 'password/reset/:reset_password_token' => 'users/passwords#edit', as: :edit_user_password
    patch 'password' => 'users/passwords#update'
    put 'password' => 'users/passwords#update', as: :update_user_password
  end

  resources :users, only: :show, :as => 'user_show' do
    resources :posts, only: [:show]
    get '/posts', :to => 'posts#users_index', :as => 'users_index'
  end
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'

  resources :posts, only: [:new, :edit]
  post '/posts/new', :to => 'posts#create'
  patch '/posts/:id/edit', :to => 'posts#update', :as => 'posts_edit'
  resources :categories do
    resources :posts, only: [:index, :show]
    post '/posts/:id', :to => 'replies#create', :as => 'reply'
  end

  if Rails.env.production?
    get '*not_found' => 'application#routing_error'
    post '*not_found' => 'application#routing_error'
  end
end

app/views/layouts/_flash.html.erb
<% if flash[:error].present? %>
<div class="notification is-info">
<%= flash[:error].html_safe %>
</div>
<% end %>
<% if flash[:alert].present? %>
<div class="notification is-info">
<%= flash[:alert].html_safe %>
</div>
<% end %>
<% if flash[:notice].present? %>
<div class="notification is-info">
<%= flash[:notice].html_safe %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
  <footer class="footer">
    <div class="has-text-centered">
      <ul class="footer-menu is-size-7">
        <li><%= link_to('利用規約', terms_path) %></li>
        <li><%= link_to('プライバシーポリシー', privacy_path) %></li>
        <li><%= link_to('お問い合わせ', inquiry_path) %></li>
      </ul>
    </div>
    <div class="content has-text-centered">
      <p class="is-size-7">© 2019 Mentally</p>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<!-- nav start-->
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to root_path, class: 'navbar-item' do %>
        <%= image_tag 'logo.png', { alt: 'Mentally', class: 'logo' } %>
      <% end %>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-menu">
      <div class="navbar-start">
      </div>
      <div class="navbar-end">
        <%= link_to 'Mentallyとは', about_path, class: 'navbar-item' %>
        <% if user_signed_in? %>
        <%= link_to '質問する', new_post_path, :class => 'navbar-item' %>
        <% end %>
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? %>
              <%= link_to user_show_path(current_user), :class => 'button is-small is-primary' do %>
                <strong><i class="fas fa-user fa-fw"></i>マイページ</strong>
              <% end %>
              <%= link_to logout_path, method: :delete, :class => 'button is-small is-light' do %>
                <i class="fas fa-sign-out-alt fa-fw"></i></i>ログアウト
              <% end %>
            <% else %>
              <%= link_to sign_up_path, :class => 'button is-small is-primary' do %>
                <strong>登録</strong>
              <% end %>
              <%= link_to login_path, :class => 'button is-small is-light' do %>
                <i class="fas fa-sign-in-alt fa-fw"></i></i>ログイン
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
<!-- nav end -->

app/views/layouts/_side.html.erb
<div class="box">
  <aside class="menu">
    <p class="menu-label">カテゴリ一覧</p>
    <ul class="menu-list">
      <% @categories.each do |category| %>
      <li class="is-size-7"><%= link_to(category.name, category_posts_path(category)) %></li>
      <% end %>
    </ul>
  </aside>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon_pkg/apple-touch-icon.png', {:rel => 'apple-touch-icon', :sizes => '120x120', :type => 'image/png'} %>
  <%= favicon_link_tag 'favicon_pkg/favicon.ico', {:rel => 'icon', :sizes => '48x48', :type => 'image/png'} %>
  <title><%= page_title %></title>
  <%= stylesheet_bundle_tag 'style', media: 'all' %>
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
<%= render 'layouts/header' %>
<!-- section start -->
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-9">
        <%= render 'layouts/flash' %>
        <%= yield %>
      </div>
      <div class="column">
        <%= render 'layouts/side' %>
      </div>
    </div>
  </div>
</section>
<!-- section end -->
<%= render 'layouts/footer' %>
<%= javascript_bundle_tag 'app' %>
<%= javascript_bundle_tag 'style' %>
</body>
</html>